### ISSUE TITLE
Add in support for Minecraft Forge

### ISSUE THREAD

**Issue by maksimetny** [Pierce01/MinecraftLauncher-core#1]
Hello! Can you please tell me how to launch a client with mods in your minecraft-launcher-core? Tried and failed. I would be very grateful for the help.

**Comment by Pierce01** [comment]
Hey there, as of right now this launcher core was built to launch versions of Minecraft from 1.7.3 to the latest stable releases. I haven't tested launching MC with forge. I'll look into it really quick! Could you post the error you're getting?


Also, thanks for taking interest in this project!

**Comment by maksimetny** [comment]
> 
> 
> Hey there, as of right now this launcher core was built to launch versions of Minecraft from 1.7.3 to the latest stable releases. I haven't tested launching MC with forge. I'll look into it really quick! Could you post the error you're getting?
> 
> Also, thanks for taking interest in this project!

Error while trying to run Forge client:

test_mc@1.0.0 start D:\Users\Maksimetny\Desktop\test_mc
node app

{ authorization:
   { access_token: '80ac39e0-21a2-11e9-b37a-432fe36c4269',
     client_token: '80ac39e1-21a2-11e9-b37a-432fe36c4269',
     uuid: '80ac39e2-21a2-11e9-b37a-432fe36c4269',
     name: 'steve',
     user_object: '{}' },
  clientPackage: null,
  root: 'D:/Users/Maksimetny/Desktop/test_mc/game',
  os: 'windows',
  version: { number: '1.8.8-forge1.8.8-11.15.0.1655', type: 'release' },
  memory: { max: '512' } }
(node:8176) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'classifiers' of undefined
    at D:\Users\Maksimetny\Desktop\test_mc\node_modules\minecraft-launcher-core\components\handler.js:114:36
    at Array.map (<anonymous>)
    at Promise (D:\Users\Maksimetny\Desktop\test_mc\node_modules\minecraft-launcher-core\components\handler.js:113:48)
    at new Promise (<anonymous>)
    at Object.module.exports.getNatives (D:\Users\Maksimetny\Desktop\test_mc\node_modules\minecraft-launcher-core\components\handler.js:103:12)
    at Object.module.exports [as core] (D:\Users\Maksimetny\Desktop\test_mc\node_modules\minecraft-launcher-core\components\launcher.js:20:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
(node:8176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:8176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

---------------------------------
If you make it possible to launch Forge and Optifina soon, I will be eternally grateful to you)

**Comment by Pierce01** [comment]
I'll explain why you're getting that error. 

The core is trying to get listed natives from an undefined `lib` since `1.8.8-forge1.8.8-11.15.0.1655` isn't listed on Minecraft's official version manifest.

Right now I don't think you'll be able to use this project to launch Minecraft forge since atm you cant add custom launch options.


However, in the future, I do plan on adding forge support! so stay tuned. If I have enough time this week I'll try to implement, however depending on school and work it might be delayed to next week

**Comment by maksimetny** [comment]
Well, thanks for the reply, waiting for the update!


вс, 27 янв. 2019 г., 19:53 Pierce notifications@github.com:

**Comment by bazerares** [comment]
Also looking forward to this update.
All the launchers for MC on JavaScript that I tried were non-working, and this one I really liked was easy to use.
The only negative, the lack of support Forge, I think you will fix it soon.

Thank you for your work!

P.S
sorry for my bad english)

**Comment by Pierce01** [comment]
Alrighty, sorry for the delay. I'm starting on it now.


I'll probably make a new branch or just not post it to github while I'm working on it, heads up!

**Comment by Pierce01** [comment]
My current idea about supporting forge is the user will need to download the Universal Forge jar before hand, and then specify the path in the launch options (probably in the version object).

The following commit does that

https://github.com/Pierce01/MinecraftLauncher-core/commit/05daffc03329745a3e0e3ddc1da283b9da9c8cfe

**Comment by maksimetny** [comment]
I tried to run forge on 1.8.8
(The wagon took from here https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.8.html)
Pointed forgeJarPath to opions, libraries were downloaded (presumably from forge), but Minecraft launched Vanilla
What am I doing wrong?

Please write the instructions :)
![image](https://user-images.githubusercontent.com/46288028/52432733-49dfe780-2b1c-11e9-8c5a-81663f9c0f4a.png)

**Comment by Pierce01** [comment]
It launches as vanilla because I haven't implemented forge into `launcher.js` yet.

Meaning: it downloads the needed resaources, but doesn't launch with the tweaked classes / mods.

I'm currently running into the following error when trying to launch with forge.

![image](https://pierce.is-serious.business/63441c.png)

I'll probabaly going to talk with one of my friends to see what im doing wrong. Hang tight!

**Comment by Pierce01** [comment]
Forge support has been added with the following commit https://github.com/Pierce01/MinecraftLauncher-core/commit/f9fc29ee6777efdc65e1d9dc2129ba82cefdfd9e

basic usage is as such

```js
mc.authenticator.getAuth("email").then(auth => {
    // Save the auth to a file so it can be used later on!
    mc.core({
        authorization: auth,
        clientPackage: null,
        root: "C:/Users/BGTest/AppData/Roaming/.mc",
        forge: {
            path: "C:\\Users\\BGTest\\Desktop\\forge-1.8.8-11.15.0.1655-universal.jar"
        },
        os: "windows",
        version: {
            number: "1.8.8",
            type: "MCC-Launcher" 
        },
        memory: {
            max: "500"
        }
    });
});
```

I'll provide more documentation when i get home. Sorry for the delay

**Comment by Pierce01** [comment]
I haven't pushed these changes to NPM yet, fyi
