### ISSUE TITLE
How do I show the log in my electron app instead of in console?

### ISSUE THREAD

**Issue by FormalSnake** [Pierce01/MinecraftLauncher-core#105]
When my app is compiled, minecraft never seems to launch, unless I launch my compiled app from console (mac)
So I want to show the log of the minecraft launcher in my electron app, doesn't matter if it's the entire electron log or not.

Like in prism launcher
<img width="1113" alt="Screenshot 2023-03-20 at 13 00 44" src="https://user-images.githubusercontent.com/90651091/226346267-53a965dd-0a6a-4566-8c9a-7876625320b4.png">

**Comment by Bricklou** [comment]
Hi,

if you check the doc [here](https://github.com/Pierce01/MinecraftLauncher-core#client-functions), you'll see that the `launch` method return a [NodeJS child process](https://nodejs.org/api/child_process.html#class-childprocess).
You can try to plug your log window on it to retrieve the logs and the game status.

**Comment by FormalSnake** [comment]
at the monent, i am trying to do it like this:
```
launcher.on("data", (e) =>
        mainWindow.webContents.send("asynchronous-message", e)
      );
```
Could this work?

**Comment by Bricklou** [comment]
yes, it is also possible to use this method.
