### ISSUE TITLE
can't join your discord

### ISSUE THREAD

**Issue by JLSkyzer** [Pierce01/MinecraftLauncher-core#109]
Hello, i can't join you discord for no reason

my id : 909862540945793094

**Comment by JLSkyzer** [comment]
yes i say "oups.. you can't join" like i'm ban

can you try to ban me and after you unban me?

**Comment by Pierce01** [comment]
What was the ID of your previously banned account?

**Comment by JLSkyzer** [comment]
> What is the ID of your banned account?

it's an account who are deleted, because my old account have been hack.

My old username is JLSkyzer ou strykerz_2_0
