### ISSUE TITLE
Error with ForgeWrapper after update

### ISSUE THREAD

**Issue by Seeroy** [Pierce01/MinecraftLauncher-core#116]
Hi. After update to 3.17.2, where you updated the version of ForgeWrapper, when you try to start the game with Forge, I get this error:
`java.lang.ClassNotFoundException: io.github.zekerzhayard.forgewrapper.installer.Main`

**Comment by Pierce01** [comment]
What version of Minecraft are you trying to launch, and which installer jar are you using?
