### ISSUE TITLE
Error with Electron

### ISSUE THREAD

**Issue by anreszii** [Pierce01/MinecraftLauncher-core#121]
ERROR in ./node_modules/verror/node_modules/extsprintf/lib/extsprintf.js 6:15-30
Module not found: Error: Can't resolve 'util' in '/Users/reszi./Documents/GitHub/electron-with-create-react-app/node_modules/verror/node_modules/extsprintf/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

**webpack compiled with 94 errors and 1 warning**
 
94 errors like this, nothing helps: creating resolve.fallback, etc.
Has anyone encountered a similar error and can help?

**Comment by Bricklou** [comment]
This error doesn't come from the library but from your own projects. You're using deprecated tools.
