### ISSUE TITLE
Failed to start due to TypeError: Cannot read properties of undefined (reading 'meta'), closing...

### ISSUE THREAD

**Issue by Withorcool** [Pierce01/MinecraftLauncher-core#123]
[MCLC]: Failed to start due to TypeError: Cannot read properties of undefined (reading 'meta'), closing...

**Comment by Pierce01** [comment]
This error is caused by passing an improper auth object in the options authorization field. Would you be able to provide more info? 

Here’s the docs showing the proper object format https://github.com/Pierce01/MinecraftLauncher-core#authentication
