### ISSUE TITLE
Authenticator should send clientToken

### ISSUE THREAD

**Issue by Coding-Kiwi** [Pierce01/MinecraftLauncher-core#19]
As stated in https://wiki.vg/Authentication calls to the /authenticate endpoint should include a clientToken.
Currently, a clientToken is generated in the `Authenticator.getAuth` function, but it is not passed to the /authenticate endpoint, as a result you get an accessToken that has no associated clientToken.

`Authenticator.validate` does not send the clientToken, currently that is correct since the accessToken is generated without one.

`Authenticator.refresh` however does send the clientToken but it is ignored since the access token is generated without one.
same for `Authenticator.invalidate`

**Comment by Pierce01** [comment]
must have missed that, thanks for pointing that out! Will fix

**Comment by Pierce01** [comment]
added
