### ISSUE TITLE
A fatal error (1.14.4)

### ISSUE THREAD

**Issue by maksimetny** [Pierce01/MinecraftLauncher-core#20]
Error starting version 1.14.4
Logs are attached:
[log.txt](https://github.com/Pierce01/MinecraftLauncher-core/files/3526245/log.txt)
[hs_err.log](https://github.com/Pierce01/MinecraftLauncher-core/files/3526246/hs_err.log)

I managed to partially solve the problem in my fork, but the following error already occurs:
![Screenshot_2](https://user-images.githubusercontent.com/46288028/63449663-30afe000-c449-11e9-9630-4eb518332296.png)

**Comment by Pierce01** [comment]
I'll investigate since I'm getting the same error as well. What's the code that partially fixes it?

**Comment by Pierce01** [comment]
Working on a fix. Sit tight

**Comment by Pierce01** [comment]
Fixed! Going to refactor the code so it looks nice and works on OSX and Linux. Should be finished today

**Comment by Pierce01** [comment]
Fix added with 3.9
