### ISSUE TITLE
Getting error while launching with Optifine

### ISSUE THREAD

**Issue by maksimetny** [Pierce01/MinecraftLauncher-core#3]
Good afternoon again
I am testing a new update 2.0.0 and have discovered that some mods are taking off with full compliance with the versions
For example, when trying to run Forge's version with Optifine in the mods folder, it gives an error:
(It was tested on version 1.8.9 with forge-1.8.9-11.15.1.1722-universal and OptiFine_1.8.9_HD_U_I7)
```
$ node app
events.js:173
    throw err; // Unhandled 'error' event
    ^
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Exception in thread "Thread-12" )
    at EventEmitter.emit (events.js:171:17)
    at Socket.minecraft.stderr.on (D:\Users\Maksimetny\Desktop\ggmc\node_modules\minecraft-launcher-core\components\launcher.js:70:4
9)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
I haven't found any more errors) Thanks for the update

**Comment by Pierce01** [comment]
Make sure you're updated to the latest version, which as of now is `2.1.1`.

Could you link me the jar so I can test over here? Sadly the error doesn't give any information (that I'm familiar with)

**Comment by maksimetny** [comment]
archived package https://vk.com/doc524118722_491307696

**Comment by Pierce01** [comment]
The file is password protected, so i cant view the contents of that jar.

**Comment by maksimetny** [comment]
Sorry, I completely forgot about the fact that I set the password.

Password - git

**Comment by Pierce01** [comment]
I'm not sure why you're getting this error. Using the jar and and the Optifine mod you provided, I was able to launch successfully 

![image](https://pierce.is-serious.business/7a8eec.png)
![image2](https://pierce.is-serious.business/941997.png)

**Comment by Pierce01** [comment]
Was looking through the version of MCLC you had, it's outdated. Please update.

Also decided to run the script with the direct files you sent me, Minecraft launches with Optifine without error. If you modified any code, just reinstall MCLC entirely.

**Comment by maksimetny** [comment]
Reinstalled minecraft-launcher-core (current version 2.1.3), and also downloaded new forge-1.8.9-11.15.1.1722-universal.jar and OptiFine_1.8.9_HD_U_I7.jar
Still the same mistake .. very strange

I attach the archive https://vk.com/doc524118722_491430659

**Comment by Pierce01** [comment]
I am able to launch in the following environment you provided. Looks like this issue is on your end.

**Comment by Pierce01** [comment]
Any update on this?

**Comment by Pierce01** [comment]
Closing as author hasn't responded in 4 days and it seems this only happens on their computer.
