### ISSUE TITLE
Launch with texturepack

### ISSUE THREAD

**Issue by dada513** [Pierce01/MinecraftLauncher-core#31]
Is there a way to launch the client with a custom texturepack loaded?

**Comment by AzureZhen** [comment]
Yes, you want set a default options.txt to be downloaded and have it include `resourcePacks:["yourresourcepack.zip"]`

**Comment by Pierce01** [comment]
Going off of @AzureZhen, you'll need to specify a clientPackage to download those needed files. Check the docs for more info 👌

**Comment by dada513** [comment]
ok, thanks
