### ISSUE TITLE
Request library is deprecated!

### ISSUE THREAD

**Issue by Coder-Iro** [Pierce01/MinecraftLauncher-core#36]
```
[1/4] Resolving packages...
warning minecraft-launcher-core > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
```

**Comment by Coder-Iro** [comment]
PLZ use axios library instead of request

**Comment by Pierce01** [comment]
Hi! I'll look into the other libraries out there for the best one, however I'm out on college visits so I won't be able to for a day or two.

**Comment by Pierce01** [comment]
Hello, lowkey forgot this issue was opened. I'm planning a rework on the handler file before I go off to college so I'll probably end up using another library like Axios or SA when that rolls around. Thanks for using the project!

**Comment by artegoser** [comment]
I can try to rewrite it myself after July 1 and send a pull request
