### ISSUE TITLE
Custom Minecraft args won't work

### ISSUE THREAD

**Issue by grallc** [Pierce01/MinecraftLauncher-core#39]
Because Custom Minecraft arguments (for [MCP](https://minecraft.gamepedia.com/Programs_and_editors/Mod_Coder_Pack) maily) won't work using `options.customArgs`, because Minecraft arguments have to be after the `-cp`.

Therefore, an `options.customLaunchArgs` options might be added.

**Comment by Pierce01** [comment]
Yep, will add this :) thank you!
