### ISSUE TITLE
Useless process in the natives function

### ISSUE THREAD

**Issue by Bricklou** [Pierce01/MinecraftLauncher-core#4]
Hello,
While I was reading your code for a personnel project, I realize that the 2 next line are useless for the installation process.
https://github.com/Pierce01/MinecraftLauncher-core/blob/2652654c1814a950f7e6f72588e7a7b11eb58e6e/components/handler.js#L131-L132
In the official Minecraft Launcher, the natives aren't extracted and are run like JAR files.

**Comment by Pierce01** [comment]
Thanks for taking interest!

When I was looking into how minecraft was being launched by the normal launcher, it was extracting the jars and placing them in a temp folder. Havent tested them without being extracted, so I'll get back to you on this!

**Comment by Pierce01** [comment]
I commented out the lines that extract the Jars, when I attempted to launch it without extracting the files, Minecraft threw the following error
![image](https://user-images.githubusercontent.com/18330673/53209304-174be980-3608-11e9-8ec8-81173f500a3a.png)
Like in the normal launcher, they need to be extracted.

**Comment by Pierce01** [comment]
Checked with a friend of mine, Jars do need to be extracted. Closing issue
