### ISSUE TITLE
How to run OptiFine?

### ISSUE THREAD

**Issue by Hyd3r1** [Pierce01/MinecraftLauncher-core#42]
I trying
`            version: {
                number: "1.8.8",
                type: "release",
                custom: "OptiFine 1.8.8"
            },`

and getting
`Error: Could not find or load main class net.minecraft.launchwrapper.Launch`

**Comment by Pierce01** [comment]
If you installed Optifine properly, your launch options should look something like this :)

![image](https://owo.whats-th.is/4kMxFNY.png)

The reason why custom is like that is that it points to the folder in version.

![image2](https://owo.whats-th.is/2pcJ7v1.png)

**Comment by Pierce01** [comment]
If you're still confused, feel free to join the discord and I'll help you :)

**Comment by Hyd3r1** [comment]
If i don't have installed optifine? And I want to run clean with OptiFine files. then I get the error "Error: Could not find or load main class net.minecraft.launchwrapper.Launch"
