### ISSUE TITLE
Issue with forge 1.13+

### ISSUE THREAD

**Issue by Pierce01** [Pierce01/MinecraftLauncher-core#43]
Not sure what's up since the class paths & everything else is the same as Mojang's, but it fails to launch. Need to look into.

(NoXe's Screenshot)
![image](https://owo.whats-th.is/uVSKkMc.png)

**Comment by NoXeDev** [comment]
there is a problem with "ModDir" in first, I will see if the installation methode is the same (PS : this issue is for 1.13+ not 1.14+)

**Comment by NoXeDev** [comment]
You can now close this issue with your commit

**Comment by Pierce01** [comment]
👌
