### ISSUE TITLE
Could not find a declaration file for module 'minecraft-launcher-core'

### ISSUE THREAD

**Issue by Happistarz** [Pierce01/MinecraftLauncher-core#49]
Hey ! 
I cannot run my build because the module doesn't have a declaration file 😢 
Plz help me 😭 i not found every where a solution for that 
i tryied to install with @types and that's don't worked
i tryied too add a declaration file with (.d.ts) that's don't worked
i don(t found the issue of this problem snif

**Comment by Pierce01** [comment]
Addressed
