### ISSUE TITLE
User properties being undefined 

### ISSUE THREAD

**Issue by maksimetny** [Pierce01/MinecraftLauncher-core#5]
![image](https://user-images.githubusercontent.com/46288028/54037253-bc50ef80-41ce-11e9-8ca4-9b219b0337e9.png)
help pls

**Comment by Pierce01** [comment]
This is created when an invalid JSON object is passed, please copy paste the core options you are passing.

**Comment by maksimetny** [comment]
array arguments:

(27) ["-XX:-UseAdaptiveSizePolicy", "-XX:-OmitStackTraceInFastThrow", "-Dfml.ignorePatchDiscrepancies=true", "-Dfml.ignoreInvalidMinecraftCertificates=true", "-Djava.library.path=C:\Users\Maksimetny\AppData\Roaming\.launcher\natives\1.7.3", "-Xmx512M", "-Xincgc", "-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump", "-cp", "C:\Users\Maksimetny\AppData\Roaming\.launcher\ver…r\libraries\tv\twitch\twitch\5.12\twitch-5.12.jar", "net.minecraft.client.main.Main", "--username", "launcher_63722", "--version", "1.7.3", "--gameDir", "C:\Users\Maksimetny\AppData\Roaming\.launcher\versions\1.7.3", "--assetsDir", "C:\Users\Maksimetny\AppData\Roaming\.launcher\assets", "--assetIndex", "1.7.3", "--uuid", "bc722cc0-41c6-11e9-86da-bd1737195f58", "--accessToken", "bc722cc0-41c6-11e9-86da-bd1737195f58", "--userProperties", undefined]

**Comment by Pierce01** [comment]
Yep, its user props being dumb. I'll fix this when I get home. Thanks for letting me know

**Comment by Pierce01** [comment]
Sorry for the wait, home now. What version of MCLC are you on? On my machine, the user_properties are not undefined when launching in both offline and online mode.

Line 14 in authenticator.js is `user_properties: JSON.stringify({})` correct?

**Comment by maksimetny** [comment]
[image: image.png]

пт, 8 мар. 2019 г. в 19:29, Pierce <notifications@github.com>:

**Comment by maksimetny** [comment]
![image](https://user-images.githubusercontent.com/46288028/54108277-8ee18d00-43ec-11e9-9457-7d8569d02d62.png)

**Comment by Pierce01** [comment]
Hmm... ok. Can you show me your code for when your initializing the core's options?

**Comment by Pierce01** [comment]
Assuming issue was a user error when saving the authorization.
