### ISSUE TITLE
Mojang to MSFT

### ISSUE THREAD

**Issue by Pierce01** [Pierce01/MinecraftLauncher-core#53]
So, there's a new authentication system coming to Minecraft which may break the current login method. 
Will investigate when changes are pushed, hoping nothing too major gets changed in the end.

https://www.minecraft.net/en-us/article/java-edition-moving-house

**Comment by realshapes** [comment]
![Screen Shot 2020-12-15 at 1 48 49 PM](https://user-images.githubusercontent.com/30955604/102258940-7618dc00-3edc-11eb-8185-631c893e89a6.png)
Found this on [this support article](https://help.minecraft.net/hc/en-us/articles/360050865492-Minecraft-Java-Edition-Account-Migration-FAQ). Looks like they have something planned for us.

**Comment by Pierce01** [comment]
Yep, i saw when it was released, just patiently waiting at this point. We have discussions about this in the discord if you're interested in joining.

**Comment by realshapes** [comment]
I am in the discord lmao, my tag is `shapes#1938`

**Comment by MuhammadUsmanMithani** [comment]
What is your Discord?

**Comment by Nishant1500** [comment]
> ![Screen Shot 2020-12-15 at 1 48 49 PM](https://user-images.githubusercontent.com/30955604/102258940-7618dc00-3edc-11eb-8185-631c893e89a6.png)
> Found this on [this support article](https://help.minecraft.net/hc/en-us/articles/360050865492-Minecraft-Java-Edition-Account-Migration-FAQ). Looks like they have something planned for us.

This is for migrated Accounts, the Accounts which are still in mojang database would work.

**Comment by MuhammadUsmanMithani** [comment]
so should offline mode accounts

**Comment by Pierce01** [comment]
Yes, we know old mojang accounts are still supported. Please keep your issue to your own issue thread or in the discord, not in this one.

**Comment by Pierce01** [comment]
Following up on a response from a backchannel, I will look into providing an example to implement the new system within your launcher. However, as the new system involves OAuth and needing to open a browser window, it will not be added directly into MCLC.

**Comment by Pierce01** [comment]
Microsoft spitting in our face with this one
![image](https://when-the.imposter-is-s.us/uploads/47f734da-5cd1-4867-bcfc-fe962d7ee831/cHXRihA2_.png)
