### ISSUE TITLE
My Client can´t start :c

### ISSUE THREAD

**Issue by ReeperkCustoms** [Pierce01/MinecraftLauncher-core#62]
My client tries to start, but the problem is that it starts minimized: https://www.vagina.guru/ti26RD . Also, when it starts, the client is completely black... :c can someone help me?

**Comment by Suyashtnt** [comment]
send the `client.launch({ .. })` part

**Comment by ReeperkCustoms** [comment]
Um do you have Discord, if so let write about it xd

**Comment by Pierce01** [comment]
The MCLC support Discord can be found here. https://discord.com/invite/8uYVbXP

**Comment by ReeperkCustoms** [comment]
Thx i joined :)
