### ISSUE TITLE
Failed to load json files for ForgeWrapper, using Vanilla instead

### ISSUE THREAD

**Issue by escapeoneone** [Pierce01/MinecraftLauncher-core#65]
I creating a simple minecraft launcher.
And on start MCLC say me `[MCLC]: Failed to load json files for ForgeWrapper, using Vanilla instead`
Why it? [Full logs](https://pastebin.com/raw/LZnrG6Sc); [Config](https://pastebin.com/99p2My7f)

**Comment by Pierce01** [comment]
For Forge 1.12.2 versions past 2847, you need to use the installer jar.
