### ISSUE TITLE
Problems installing the fabric

### ISSUE THREAD

**Issue by arajooj** [Pierce01/MinecraftLauncher-core#68]
Hi, I'm having problems installing the fabric in my customized launcher folder.

Opts:
![image](https://user-images.githubusercontent.com/37886774/113525979-593d0d00-958e-11eb-970e-7fee0c8df238.png)

Folder:
![image](https://user-images.githubusercontent.com/37886774/113525990-6e19a080-958e-11eb-8f89-25bcb9259e3e.png)

Error:
![image](https://user-images.githubusercontent.com/37886774/113525998-7b368f80-958e-11eb-9b9d-10d6b1ecfce5.png)

Error in text:

`21:28:35.389 [main] ERROR FabricLoader - Could not find valid game provider!

Exception in thread "main" java.lang.RuntimeException: Could not find valid game provider!
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:96)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

21:28:35.390 [main] ERROR FabricLoader - - Minecraft`

**Comment by Pierce01** [comment]
When using fabric, you need to use the JSON file that's generated for Technic.

**Comment by arajooj** [comment]
Everything went well, thank you very much.
