### ISSUE TITLE
Add in support for Optifine-Client or other custom clients

### ISSUE THREAD

**Issue by D0an** [Pierce01/MinecraftLauncher-core#7]
Hello! Is there any way to open a custom client, such as versions/1.7.10-Optifine_HD_U_E7, or just a custom / modified client in general? I tried to open the game, but couldn't manage to find out how to do it the way I want it. I'd really appreciate if you could help me achieve this.

**Comment by Pierce01** [comment]
As of now, you can only use vanilla and forge. When I get home I'll get to work on adding the feature. Thanks for taking interest in the project :)

**Comment by Pierce01** [comment]
Hey there, here's my follow up notes! I'll be adding support for custom jars, however, you'll need to provide the needed files (in this case, files for Optifine) which can be acomplished by using the `clientPackage` option. The main reason why is I don't want to add too much bloat to this project.

My proposed idea for the config would be

```json
"version": {
    "number": "1.12.2",
    "type": "release",
    "jar": "1.12.2-OptiFine_HD_U_E3"
}
```
why am I only providing an option for the jar?

well if we're following the practice of normal Minecraft, they have the json, folder, and the jar named the same thing!

![image](https://pierce.is-serious.business/4hqeY6r.png)

Did you have something else in mind? Feel free to say below ^^

**Comment by D0an** [comment]
That looks really good! I had one more thing I was going to ask about: Would it be possible for you to make a way to change the location of the version, but not the minecraft directory?

**Comment by Pierce01** [comment]
Wdym change location of the version? As in allow the user to specify a custom version folder path? That's already being proposed above. The reason why I'm keeping number the way it is since MCLC still needs to add the normal class paths while also adding in the custom ones. 

While debugging yesterday I ran into a few issues, so I'm not sure how long this'll take to implement

**Comment by D0an** [comment]
Yeah I ment it in the way you proposed above, I read over it. Also there isn't any hurry for this to be done. Thanks for putting your time into trying to get this to work :) really appreciate it!

**Comment by Pierce01** [comment]
Fixed my error, was a silly one. Nitpicking things now so i should have this done in a couple of hours

**Comment by Pierce01** [comment]
All done! Commit https://github.com/Pierce01/MinecraftLauncher-core/commit/c767fb0685118d97bebac03dcfd54bf93fb82e85 adds in this feature. I ended up changing `jar` to `custom` since that made more sense

here's a basic example
```js
launcher.core({
    authorization: login,
    clientPackage: null,
    root: config.root,
    os: "windows",
    version: {
        number: "1.12.2",
        type: "release",
        custom: "1.12.2-OptiFine_HD_U_E3"
    },
    memory: {
        max: "2000",
        min: "1000"
    }
});
```
