### ISSUE TITLE
Microsoft authentification

### ISSUE THREAD

**Issue by luuxis** [Pierce01/MinecraftLauncher-core#74]
hello I created a Minecraft launcher from a library based on Minecraft launcher core (I am now at the Microsoft authentication part)

I would like to know do you have a discord server so that one can help me to set up the Microsoft authentication part

**Comment by Matix-Media** [comment]
Hi, @luuxis ,
Microsoft Authentication itself is not integrated into mclc. However, you can use a 3rd party library like [msmc ](https://www.npmjs.com/package/msmc)to authenticate using Microsoft. For further questions, visit the discord at https://discord.gg/DPXU6kKDUA

**Comment by luuxis** [comment]
thank you

**Comment by FieryMewtwo** [comment]
Hi, I'm very new to Java and am unsure how to use msmc with mclc. It has code, but doesn't tell anything about where it needs to go in the repo.

**Comment by Pierce01** [comment]
Look at MSMC’s repo.

**Comment by Matix-Media** [comment]
> Hi, I'm very new to Java and am unsure how to use msmc with mclc. It has code, but doesn't tell anything about where it needs to go in the repo.

Hi, this is not a java project. This library (and msmc) is written in JavaScript and is therefore not compatible with java.
