### ISSUE TITLE
Certificate expired when the module download forge libraries

### ISSUE THREAD

**Issue by ItsBursty** [Pierce01/MinecraftLauncher-core#80]
The module can't download forge and give me this error who said the certificate has expired:
<img width="1157" alt="Capture d’écran 2021-10-10 192308" src="https://user-images.githubusercontent.com/76739818/136706575-1dfb76ec-0653-4948-bfe4-70e8e63272f6.png">

I can't do anything actually and i don't know how to solve that 😢

**Comment by Pierce01** [comment]
Not a MCLC problem. This comment should shed some light on your issue. https://github.com/node-fetch/node-fetch/issues/568#issuecomment-932435180
