### ISSUE TITLE
Error when trying to use clientPackage

### ISSUE THREAD

**Issue by GamesX50** [Pierce01/MinecraftLauncher-core#81]
Hi, I'm creating my own launcher and I'm using clientPackage to install from a website and put it in my launcher. The problem is that copy the file in the directory minecraft instead of versions and give me error. I fixed it changing the line 658 of handler.js:

new Zip(options.clientPackage).extractAllTo(options.root + "/versions", true)

I changed the extract route of root to versions and works fine.

**Comment by Pierce01** [comment]
clientPackage is meant to download other files as well. If you want to have client package download a custom version, you need to have a folder called versions, then have the custom version folder inside that folder.
