### ISSUE TITLE
error on "gpu_init.cc" on launching game : "passthrough is not supported"

### ISSUE THREAD

**Issue by bouchbi** [Pierce01/MinecraftLauncher-core#82]
Hi, I have a pretty weird issue, after the my-launcher-core implementation to launch the game, I tried it and everything was working fine.
However, now it throws an error just after extracting client package.

It is the following:
"[8248:1225/203934.854:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is"

This is even more weird because I don't have the end of the sentence.

If you have an idea of why this is occuring, please tell me.
Thanks for your help

**Comment by spjoes** [comment]
Thought it was just me! Great to hear others have the problem aswell.

**Comment by Pierce01** [comment]
Looks like this is an electron related issue, give this read, might be able to help. https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled
