### ISSUE TITLE
SyntaxError · Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by ovchinnikov** [Pierce01/MinecraftLauncher-core#94]
Hi, 
Some of my users have the following error "SyntaxError · Unexpected token u in JSON at position 0"
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/1101267/188874346-3560989f-ca7b-4441-94ab-b9ef9ccdf90f.png">

[MCLC]: MCLC version 3.16.16

Does anyone know how to solve it?

**Comment by ovchinnikov** [comment]
Probably need to add "return" in line 116

**Comment by Pierce01** [comment]
Yep, that looks like it would cause the issue. I'll add return when I get home from work._
